force-app/main/default/objects/AA_Send_Email_Event__e/AA_Send_Email_Event__e.object-meta.xml
<CustomObject>
    <label>AA Send Email Event</label>
    <pluralLabel>AA Send Email Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/AA_Send_Email_Event__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>json payload</description>
    <label>Payload</label>
    <length>131070</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AA_EmailService.cls
public class AA_EmailService {
    
    public static void publishEmail(AA_EmailRequest request) {
        AA_Logger logger = new AA_Logger(true); // En el contexto síncrono, podemos publicar inmediatamente
        AA_Send_Email_Event__e evt = new AA_Send_Email_Event__e();
        evt.Payload__c = JSON.serialize(request);
        
        Database.SaveResult sr = EventBus.publish(evt);
        
        if (!sr.isSuccess()) {
            for(Database.Error err : sr.getErrors()) {
                logger.error('Error publicando el evento de email: ' + err.getMessage());
            }
        }
    }
}