force-app/main/default/objects/AA_Appointment__c/AA_Appointment__c.object-meta.xml
<CustomObject>
    <label>AA Appointment</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>AA Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AA Appointment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AA_Appointment__c/fields/Business_Id__c.field-meta.xml
<CustomField>
    <fullName>Business_Id__c</fullName>
    <formula>Service__r.Business_Branch__r.Business__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AA_Appointment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>AA_Customer__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AA_Appointment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>AA_Employee__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AA_Appointment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>AA_Service__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AA_Appointment__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AA_Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AA_Customer__c/AA_Customer__c.object-meta.xml
<CustomObject>
    <label>AA Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AA Customer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AA_Customer__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AA_Customer__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AA_Employee__c/AA_Employee__c.object-meta.xml
<CustomObject>
    <label>AA Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AA Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AA_Employee__c/fields/Business_Branch__c.field-meta.xml
<CustomField>
    <fullName>Business_Branch__c</fullName>
    <label>Business Branch</label>
    <referenceTo>AA_Business_Branch__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AA_Employee__c/fields/Business_Id__c.field-meta.xml
<CustomField>
    <fullName>Business_Id__c</fullName>
    <formula>Business_Branch__r.Business__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AA_Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AA_Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AA_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User used for login</description>
    <inlineHelpText>User used for login</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AA_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AA_Service__c/AA_Service__c.object-meta.xml
<CustomObject>
    <label>AA Service</label>
    <nameField>
        <label>AA Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AA Service</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AA_Service__c/fields/Business_Branch__c.field-meta.xml
<CustomField>
    <fullName>Business_Branch__c</fullName>
    <label>Business Branch</label>
    <referenceTo>AA_Business_Branch__c</referenceTo>
    <relationshipLabel>Service</relationshipLabel>
    <relationshipName>Service</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AA_SalonAppointmentsController.cls
public with sharing class AA_SalonAppointmentsController {

    @AuraEnabled(cacheable=true)
    public static List<AA_Appointment__c> getSalonAppointments2() {
        return new List<AA_Appointment__c>();
    }

	@AuraEnabled(cacheable=true)
    public static List<AA_Appointment__c> getSalonAppointments() {
		 AA_Logger logger = new AA_Logger(true);
        
		String businessId = 'a02gL00000Ix6AH';
        try {
            // 1. Identificamos al usuario de la comunidad que está navegando el Back Office
            Id currentUserId = UserInfo.getUserId();
			logger.info('getSalonAppointments for user id '+currentUserId);
            
            // 2. Buscamos el registro de empleado vinculado a ese usuario para extraer su sucursal
            List<AA_Employee__c> employees = [
                SELECT Id, Business_Branch__c, Business_Id__c
                FROM AA_Employee__c 
                WHERE User__c = :currentUserId 
                LIMIT 1
            ];
            
            // Si el usuario no está configurado como empleado, retornamos una lista vacía de seguridad
            //if (employees.isEmpty()) {
             //   return new List<AA_Appointment__c>();
            //}
            
            //Id branchId = employees[0].Business_Branch__c;
			//Id businessId = employees[0].Business_Id__c;
			//businessId = 'a02gL00000Ix6AHQAZ'.left(15);

			
            
            // 3. Traemos las citas activas pertenecientes únicamente a este business (todos los branches)
            List<AA_Appointment__c> appointments =  [
                SELECT Id, Start_Date_Time__c, Status__c,
                       Customer__r.First_Name__c, Customer__r.Last_Name__c,
                       Service__r.Name, Employee__r.Name
                FROM AA_Appointment__c
                WHERE Business_Id__c = :businessId
                ORDER BY Start_Date_Time__c ASC
				LIMIT 1000
            ];
			logger.info('getSalonAppointments, size: '+appointments.size()+' business id: '+businessId);
			return appointments;
        } catch (Exception e) {
			 String message = 'error getting appointments for the business '+businessId+' '+e.getMessage()+' '+e.getStackTraceString();
            logger.error(message);
            throw new AuraHandledException(message);
        }
    }

}