force-app/main/default/objects/AA_Appointment__c/AA_Appointment__c.object-meta.xml
<CustomObject>
    <label>AA Appointment</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>AA Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AA Appointment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AA_Appointment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Service__r.Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AA_Appointment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>AA_Customer__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AA_Appointment__c/fields/Duration_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_Minutes__c</fullName>
    <formula>Service__r.Duration_Minutes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration Minutes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AA_Appointment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>AA_Employee__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AA_Appointment__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <formula>Start_Date_Time__c + (Duration_Minutes__c / 1440)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AA_Appointment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>AA_Service__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AA_Appointment__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AA_Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AA_Business__c/AA_Business__c.object-meta.xml
<CustomObject>
    <label>AA Business</label>
    <nameField>
        <label>AA Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AA Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AA_Business__c/fields/Business_Phone_Id__c.field-meta.xml
<CustomField>
    <fullName>Business_Phone_Id__c</fullName>
    <label>Business Phone Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AA_Business__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email to send messages from the app. Typically this email is the salon&apos;s owner</description>
    <inlineHelpText>Email to send messages from the app. Typically this email is the salon&apos;s owner</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/AA_Business__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>This phone number will be used for &quot;write a text message to us for more info&quot;</description>
    <inlineHelpText>This phone number will be used for &quot;write a text message to us for more info&quot;</inlineHelpText>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/AA_Business_Branch__c/AA_Business_Branch__c.object-meta.xml
<CustomObject>
    <label>AA Business Branch</label>
    <nameField>
        <label>AA Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AA Business Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AA_Business_Branch__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <referenceTo>AA_Business__c</referenceTo>
    <relationshipLabel>Business Branch</relationshipLabel>
    <relationshipName>Business_Branch</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AA_Customer__c/AA_Customer__c.object-meta.xml
<CustomObject>
    <label>AA Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AA Customer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AA_Customer__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <referenceTo>AA_Business__c</referenceTo>
    <relationshipLabel>Customer</relationshipLabel>
    <relationshipName>Customer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AA_Customer__c/fields/Comments_From_Customer__c.field-meta.xml
<CustomField>
    <fullName>Comments_From_Customer__c</fullName>
    <description>Comments provided from the customer</description>
    <inlineHelpText>Comments provided from the customer</inlineHelpText>
    <label>Comments From Customer</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AA_Customer__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AA_Customer__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AA_Customer__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/AA_Employee__c/AA_Employee__c.object-meta.xml
<CustomObject>
    <label>AA Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AA Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AA_Employee__c/fields/Business_Branch__c.field-meta.xml
<CustomField>
    <fullName>Business_Branch__c</fullName>
    <label>Business Branch</label>
    <referenceTo>AA_Business_Branch__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AA_Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AA_Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AA_Service__c/AA_Service__c.object-meta.xml
<CustomObject>
    <label>AA Service</label>
    <nameField>
        <label>AA Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AA Service</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AA_Service__c/fields/AA_Service_Category__c.field-meta.xml
<CustomField>
    <fullName>AA_Service_Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AA Service Category</label>
    <referenceTo>AA_Service_Category__c</referenceTo>
    <relationshipLabel>Service</relationshipLabel>
    <relationshipName>Service</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AA_Service__c/fields/Business_Branch__c.field-meta.xml
<CustomField>
    <fullName>Business_Branch__c</fullName>
    <label>Business Branch</label>
    <referenceTo>AA_Business_Branch__c</referenceTo>
    <relationshipLabel>Service</relationshipLabel>
    <relationshipName>Service</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AA_Service__c/fields/Duration_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_Minutes__c</fullName>
    <label>Duration Minutes</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AA_Service__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AA_Service_Category__c/AA_Service_Category__c.object-meta.xml
<CustomObject>
    <description>Ej: Manos, Manos y Pies, Cejas. Cada Service debe tener una category</description>
    <label>AA Service Category</label>
    <nameField>
        <label>AA Service Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AA Service Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AA_Service_Category__c/fields/Business_Branch__c.field-meta.xml
<CustomField>
    <fullName>Business_Branch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Branch</label>
    <referenceTo>AA_Business_Branch__c</referenceTo>
    <relationshipLabel>Service Categories</relationshipLabel>
    <relationshipName>Service_Categories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AA_Service_Category__c/fields/Description_Short__c.field-meta.xml
<CustomField>
    <fullName>Description_Short__c</fullName>
    <label>Description Short</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AA_PublicAgendaController.cls
public without sharing class AA_PublicAgendaController {
    
    private static Id BRANCH_ID = 'a03gL00000YGsWJQA1'; 
    private static String BUSSINESS_PHONE_ID = '1036897699507386';
    
    @AuraEnabled(cacheable=false)
    public static AA_Customer__c getOrCreateCustomer(String phoneNumber){
        AA_Logger logger = new AA_Logger(true);
        logger.info('getOrCreateCustomer, phoneNumber '+phoneNumber);
        // TODO for now we assume we have only one business
        AA_Business__c  business = getBusiness();
        //String fullName = 'guest'; 
        
        List<AA_Customer__c> customers = [SELECT Id, Name, Email__c, Phone_Number__c, Business__r.Business_Phone_Id__c  
                                          FROM AA_Customer__c 
                                          WHERE Phone_Number__c = :phoneNumber LIMIT 1];
        if(!customers.isEmpty()){
            logger.info('getOrCreateCustomer, customer found by found number '+phoneNumber);
            return customers.get(0);
        }else{
            logger.info('getOrCreateCustomer, a new customer will be created with the phone '+phoneNumber);
            AA_Customer__c customer = new AA_Customer__c();
            customer.Name  = phoneNumber;
            customer.Phone_Number__c = phoneNumber;
            customer.Business__c = business.Id;
            insert customer;
            return customer;
        }
    }
    
    @AuraEnabled(cacheable=false)
    public static AA_Customer__c updateCustomer(Id customerId, String firstName, String lastName, String email, String comments){
        AA_Logger logger = new AA_Logger(true);
        logger.info('updateCustomer, customerId '+customerId+ ' firstName: '+firstName+' lastName: '+lastName+' email: '+email+' comments: '+comments);
        try{

            AA_Customer__c customer = new AA_Customer__c(
                Id = customerId,
                Name = firstName+' '+lastName ,
                First_Name__c = firstName,
                Last_Name__c = lastName,
                Email__c = email,
                Comments_From_Customer__c = comments
            );

            update customer;
            logger.info('customer updated, customerId '+customerId+ ' firstName: '+firstName+' lastName: '+lastName+' email: '+email+' comments: '+comments);
            return customer;
        }catch(Exception e){
            String message = 'error updating customer: '+e.getMessage()+' '+e.getStackTraceString();
            logger.error(message);
            throw new AuraHandledException(message);
        }
        
    }
    
    private static AA_Business__c getBusiness(){
        
        List<AA_Business__c> businesses = [SELECT Id FROM AA_Business__c 
                                           WHERE Business_Phone_Id__c = :BUSSINESS_PHONE_ID
                                           LIMIT 1];
        if(businesses.isEmpty()){
            throw new HandledException('business not found by phone number id '+BUSSINESS_PHONE_ID);
        }
        return businesses.get(0);
    }
    
    private static AA_Business_Branch__c getBusinessBranch(Id businessId){
        List<AA_Business_Branch__c> branches = [SELECT Id FROM AA_Business_Branch__c 
                                                WHERE Business__c = :businessId
                                                ORDER BY CreatedDate DESC
                                                LIMIT 1];
        
        // TODO assuming for now that there is only one branch
        return branches.get(0);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<AA_Service_Category__c> getCategories() {
        AA_Logger logger = new AA_Logger(true);
        logger.info('getCategories, branch id '+BRANCH_ID);
        List<AA_Service_Category__c> categories = [
            SELECT Id, Name, Description_Short__c 
            FROM AA_Service_Category__c 
            WHERE Business_Branch__c = :BRANCH_ID
            // Sugerencia: podrías agregar un campo 'Order__c' para controlar la posición
            ORDER BY Name ASC 
            LIMIT 100
        ];
        logger.info('categories: '+JSON.serializePretty(categories));
        
        return categories;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<AA_Service__c> getServices() {
        AA_Logger logger = new AA_Logger(true);
        logger.info('getServices, branch id '+BRANCH_ID);
        List<AA_Service__c>  services =  [SELECT Id, Name, Duration_Minutes__c, Price__c, AA_Service_Category__c
                                          FROM AA_Service__c 
                                          WHERE Business_Branch__c = :BRANCH_ID
                                          LIMIT 100];
        
        logger.info('services: '+JSON.serializePretty(services));
        
        return services;
    }

    @AuraEnabled(cacheable=false)
    public static List<AA_AvailableSlot> getAvailableSlots(Id serviceId, String targetDateStr) {
        // 1. Convertimos el string que llega de JS ('YYYY-MM-DD') al tipo Date de Apex
        AA_Logger logger = new AA_Logger(true);
        logger.info('getting available slots for service: '+serviceId+' targetDateStr: '+targetDateStr);
        Date targetDate = Date.valueOf(targetDateStr);
        
        
        logger.info('getting available slots for service: '+serviceId+' and date: '+targetDate);
        List<AA_AvailableSlot> slots =  AA_AppointmentService.getAvailableSlots(serviceId, targetDate);
        logger.info(JSON.serializePretty(slots));
        return slots;
        
    }

    @AuraEnabled(cacheable=false)
    public static AA_Appointment__c saveAppointment(Id customerId, Id employeeId, Id serviceId, String dayString, String hourString) {
        AA_Logger logger = new AA_Logger(true);
        logger.info('saveAppointment customerId: '+customerId+' employeeId: '+employeeId+' serviceId: '+serviceId+' dayString: '+dayString+' hourString: '+hourString);
        try {
            // Llamamos a tu clase de servicio para mantener la lógica separada
            AA_Appointment__c appointment = AA_AppointmentService.saveAppointment(customerId, employeeId, serviceId, dayString, hourString);
            logger.info('appointment created, id: '+appointment.Id);
            return appointment;
        } catch (Exception e) {
             logger.error('error updating customer: '+e.getMessage()+' '+e.getStackTraceString());
            // Empaquetamos el error para que el LWC lo entienda correctamente
            throw new AuraHandledException('Error al confirmar la reserva: ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=false)
    public static List<AA_Appointment__c> getMisTurnos(String celular) {
        // Limpiamos el número por si el usuario ingresó espacios o guiones
        String cleanPhone = celular != null ? celular.replaceAll('[^0-9]', '') : '';
        
        return [
           SELECT Id, Name, Employee__r.Name, Start_Date_Time__c, End_Date_Time__c, Duration_Minutes__c, Service__r.Name, 
           Status__c, Customer__r.Name, Amount__c 
           FROM AA_Appointment__c 
           WHERE Customer__r.Phone_Number__c = :celular 
           AND Start_Date_Time__c >= TODAY  
           AND Service__r.Business_Branch__c = :BRANCH_ID
           AND Status__c = 'Pending'
           ORDER BY Start_Date_Time__c ASC
            LIMIT 10
        ];
    }

    @AuraEnabled(cacheable=false)
    public static void cancelarAppointment(Id appointmentId) {
         AA_Logger logger = new AA_Logger(true);
        logger.info('cancelarAppointment appointmentId: '+appointmentId);
        try {
            AA_Appointment__c app = new AA_Appointment__c(
                Id = appointmentId,
                Status__c = 'Cancelled'
            );
            update app;
        } catch (Exception e) {
             logger.error('cancelarAppointment error: '+e.getMessage()+' '+e.getStackTraceString());
            throw new AuraHandledException('Error al cancelar el turno: ' + e.getMessage());
        }
    }
    
}