force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>WARNING</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Logger.cls
public without sharing class Logger {

    private List<Log__c> logs;
    
    public Logger(){
        this.logs = new List<log__c>();
    }

    public void info(String message){
        log('INFO', message);
    }
    
    public void error(String message){
        log('ERROR', message);
    }
    
    private void log(String level, String message){
        Log__c log = new Log__c();
        log.Level__c = level;
        log.Log__c = message;
        logs.add(log);
        System.debug(level + ' '+ message);
        this.publish(); // TODO remove this
    }
    
    public void publish(){
        if(this.logs != null && !this.logs.isEmpty()){
            insert logs;
            this.logs.clear();
        }
        
    }
}